import { type CarouselSlide } from "../app/components/DesignCarousel";

export type Project = {
  id: number;
  name: string;
  category: string;
  description: string;
  gradient: string;
  accentColor: string;
  mockup: string;
  features: string[];
  testimonial: string;
  slides: CarouselSlide[];
};

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: "Barbershop",
    category: "Beauté & Coiffure",
    description: "Un salon de coiffure premium avec réservation, galerie et image de marque soignée.",
    gradient: "from-amber-500/20 via-orange-500/10 to-red-500/5",
    accentColor: "amber",
    mockup: "💈",
    features: ["Réservation", "Galerie", "Avis clients", "Tarifs"],
    testimonial: "Nous avons augmenté nos rendez-vous de 180% en 3 mois.",
    slides: [
      {
        label: "L'univers",
        caption: "Découvrez l'ambiance premium de votre futur salon et l'expérience proposée Ã  vos clients.",
        type: "video",
        src: "/video_barber.mp4",
      },
      {
        label: "Réserver",
        caption: "Un site pensé pour générer des clients, pas juste des visites.",
        type: "photo",
        src: "/barber_interface.png",
        alt: "Interface web de barbier",
      },
      {
        label: "Nos clients",
        caption: "Des clients satisfaits qui reviennent.",
        type: "photo",
        src: "/client_barber.png",
        alt: "Client satisfait",
      },
    ],
  },
  {
    id: 2,
    name: "Restaurant",
    category: "Restaurant Gastronomique",
    description: "Une présence élégante avec menu digital, réservations et storytelling visuel.",
    gradient: "from-red-500/20 via-pink-500/10 to-rose-500/5",
    accentColor: "red",
    mockup: "🍽️",
    features: ["Menu digital", "Réservations", "Photos HD", "Localisation"],
    testimonial: "Le design élégant de notre site a changé la perception de notre restaurant.",
    slides: [
      {
        label: "L'univers",
        caption: "Une vidéo immersive pour faire ressentir l'ambiance du restaurant avant la réservation.",
        type: "video",
        src: "/video_resto.mp4",
      },
      {
        label: "L'univers",
        caption: "Une salle chaleureuse, des plats soignés et une identité visuelle qui donne envie de venir.",
        type: "photo",
        src: "/univers_restau.jpg",
        alt: "Univers visuel premium pour restaurant",
      },
      {
        label: "Réserver",
        caption: "Réservation en ligne, menu digital et parcours pensé pour convertir vos visiteurs en clients.",
        type: "photo",
        src: "/site_restau.jpeg",
        alt: "Interface du site web du restaurant",
      },
      {
        label: "Réserver",
        caption: "Une interface restaurant premium qui présente le menu, rassure le client et facilite la prise de table.",
        type: "photo",
        src: "/restaurant-site.png",
        alt: "Nouvelle interface de site web restaurant avec réservation",
      },
      {
        label: "Le résultat",
        caption: "Tables réservées en avance, file d'attente en ligne, réputation renforcée.",
        type: "outcome",
        variant: "restaurant",
        src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80&auto=format&fit=crop",
        alt: "Clients dÃ®nant dans un restaurant animé",
        metrics: [
          { value: "+120%", label: "Réservations web" },
          { value: "3Ã—", label: "Visibilité locale" },
          { value: "85%", label: "Taux de remplissage" },
          { value: "+45%", label: "Avis en ligne" },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Fitness & Coaching",
    category: "Salle de sport & Coach sportif",
    description: "Un site premium pour présenter vos programmes, attirer de nouveaux clients et faciliter les prises de rendez-vous.",
    gradient: "from-lime-500/20 via-green-500/10 to-emerald-500/5",
    accentColor: "lime",
    mockup: "🏋️‍♀️",
    features: ["Programmes", "Coaching", "Prise de rendez-vous", "Transformation"],
    testimonial: "Le nouveau site a renforcé notre image et augmenté les demandes de coaching.",
    slides: [
      {
        label: "L'univers",
        caption: "Une identité forte qui inspire confiance et donne envie de commencer sa transformation.",
        type: "photo",
        src: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80&auto=format&fit=crop",
        alt: "Salle de sport moderne et coaching sportif",
      },
      {
        label: "Votre site",
        caption: "Une page d'accueil moderne conÃ§ue pour convertir vos visiteurs en nouveaux clients.",
        type: "photo",
        src: "/site_gym.jpeg",
        alt: "Interface du site web d'une salle de sport",
      },
      {
        label: "Prendre rendez-vous",
        caption: "Réservation de séances, présentation des programmes et prise de contact en quelques clics.",
        type: "photo",
        src: "/site_fit.png",
        alt: "Page de réservation d'un coach sportif",
      },
    ],
  },
  {
    id: 4,
    name: "Location de véhicules",
    category: "Mobilité",
    description: "Un site premium pour présenter votre flotte, les disponibilités et simplifier les réservations.",
    gradient: "from-sky-500/20 via-cyan-500/10 to-slate-500/5",
    accentColor: "sky",
    mockup: "🚗",
    features: ["Réservation", "Disponibilités", "Tarifs", "Mobile"],
    testimonial: "Le parcours mobile a rendu la réservation plus simple et plus premium.",
    slides: [
      {
        label: "L'univers",
        caption: "Une vidéo dynamique pour montrer la disponibilité, la confiance et l'expérience de location.",
        type: "video",
        src: "/video_loca.mp4",
      },
      {
        label: "L'univers",
        caption: "Une expérience moderne pour des services de mobilité haut de gamme.",
        type: "photo",
        src: "/location_car.jpeg",
        alt: "Interface web de location de voiture",
      },
      {
        label: "Réserver",
        caption: "Une expérience moderne pour des services de mobilité haut de gamme.",
        type: "photo",
        src: "/site_car.jpeg",
        alt: "Interface web de location de voiture",
      },
      {
        label: "Réserver",
        caption: "Un parcours clair pour choisir, réserver et confirmer votre véhicule rapidement.",
        type: "photo",
        src: "/site_location.png",
        alt: "Réservation de véhicule en ligne",
      },
      {
        label: "Nos clients",
        caption: "Des utilisateurs satisfaits qui reviennent pour une location simple et fiable.",
        type: "photo",
        src: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80&auto=format&fit=crop",
        alt: "Clients heureux avec leur voiture de location",
      },
    ],
  },
  {
    id: 5,
    name: "Nettoyage automobile",
    category: "Service / entretien",
    description: "Une expérience rapide et propre pour des réservations, des prestations et une image professionnelle.",
    gradient: "from-cyan-500/20 via-blue-500/10 to-slate-500/5",
    accentColor: "cyan",
    mockup: "🧽",
    features: ["Réservation", "Prestations", "Avis", "Localisation"],
    testimonial: "Nous avons rendu le service plus crédible et plus simple Ã  réserver.",
    slides: [
      {
        label: "L'univers",
        caption: "Une proposition claire, moderne et rassurante pour des services de qualité.",
        type: "photo",
        src: "/clean_car.jpeg",
        alt: "Interface web de nettoyage de voiture",
      },
      {
        label: "Réserver",
        caption: "Un formulaire rapide pour choisir votre prestation de nettoyage en un clin d'Å“il.",
        type: "photo",
        src: "/clean_car.png",
        alt: "Réservation de nettoyage automobile",
      },
      {
        label: "Nos clients",
        caption: "Des clients rassurés par une interface professionnelle et une prise de rendez-vous rapide.",
        type: "photo",
        src: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80&auto=format&fit=crop",
        alt: "Client satisfait aprÃ¨s nettoyage auto",
      },
    ],
  },
  {
    id: 6,
    name: "Vente de vêtements",
    category: "Vêtements / e-commerce",
    description: "Une boutique visuelle pensée pour mettre en avant vos produits et convertir rapidement.",
    gradient: "from-rose-500/20 via-pink-500/10 to-fuchsia-500/5",
    accentColor: "rose",
    mockup: "👚",
    features: ["Catalogue", "Paiement", "Marque", "Conversion"],
    testimonial: "Le site a permis d'améliorer la perception de marque et les ventes.",
    slides: [
      {
        label: "L'univers",
        caption: "Un univers visuel premium, pensé pour faire rayonner les produits.",
        type: "photo",
        src: "/vetment.jpeg",
        alt: "Interface web de site de vÃªtements",
      },
      {
        label: "Réserver",
        caption: "Une page boutique élégante pour ajouter rapidement au panier et finaliser l'achat.",
        type: "photo",
        src: "/site_vetment.png",
        alt: "Parcours d'achat en ligne pour vÃªtements",
      },
      {
        label: "Nos clients",
        caption: "Une expérience client claire et élégante, pensée pour fidéliser et convertir.",
        type: "photo",
        src: "/client_vetment.jpeg",
        alt: "Clients satisfaits achetant des vêtements en ligne",
      },
    ],
  },
  {
    id: 7,
    name: "Artisan",
    category: "Entreprise locale",
    description: "Un site professionnel pour présenter votre savoir-faire et générer des devis qualifiés.",
    gradient: "from-violet-500/20 via-purple-500/10 to-indigo-500/5",
    accentColor: "violet",
    mockup: "🛠️",
    features: ["Devis", "Portfolio", "Avis", "Contact"],
    testimonial: "Notre présence en ligne a complÃ¨tement transformé notre activité.",
    slides: [
      {
        label: "L'univers",
        caption: "Un site qui transmet confiance, clarté et sérieux dÃ¨s le premier regard.",
        type: "photo",
        src: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=80&auto=format&fit=crop",
        alt: "Professionnel artisanat",
      },
      {
        label: "Réserver",
        caption: "Un parcours simple pour demander un devis ou prendre contact.",
        type: "photo",
        src: "/site_artisan.png",
        alt: "Interface de site web pour artisan",
      },
      {
        label: "Nos clients",
        caption: "Des artisans qui ont transformÃ© leur activitÃ© grÃ¢ce Ã  un site professionnel.",
        type: "photo",
        src: "/client_artisan.jpeg",
        alt: "Client artisan satisfait",
      },
    ],
  },
  {
    id: 8,
    name: "Immobilier",
    category: "Immobilier",
    description: "Une expérience claire pour mettre en avant les biens et accélérer les prises de contact.",
    gradient: "from-indigo-500/20 via-violet-500/10 to-purple-500/5",
    accentColor: "indigo",
    mockup: "🏠",
    features: ["Biens", "Visites", "Contact", "Conversion"],
    testimonial: "Le site a fortement simplifié le parcours de nos prospects.",
    slides: [
      {
        label: "L'univers",
        caption: "Un design sobre, premium et rassurant, pensé pour valoriser chaque bien immobilier et inspirer confiance dÃ¨s la premiÃ¨re visite.",
        type: "photo",
        src: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80&auto=format&fit=crop",
        alt: "Bien immobilier premium",
      },
      {
        label: "Réserver",
        caption: "Présentation des biens et prise de contact en quelques clics.",
        type: "photo",
        src: "/site_immobilier.jpeg",
        alt: "Interface du site immobilier",
      },
      {
        label: "Nos clients",
        caption: "Des clients accompagnés dans leurs projets immobiliers grÃ¢ce Ã  une expérience digitale claire, fluide et professionnelle.",
        type: "photo",
        src: "/client_maison.jpeg",
        alt: "Clients satisfaits dans le secteur immobilier",
      },
    ],
  },
  {
    id: 9,
    name: "Salon de beauté",
    category: "Beauté & spa",
    description: "Un site premium pour séduire, réserver et faire rayonner votre salon.",
    gradient: "from-pink-500/20 via-fuchsia-500/10 to-purple-500/5",
    accentColor: "pink",
    mockup: "💅",
    features: ["Réservation", "Galerie", "Avis", "Brand"],
    testimonial: "Le design a transformé l'image de notre salon et les réservations.",
    slides: [
      {
        label: "L'univers",
        caption: "Une identité visuelle élégante pour un salon moderne et haut de gamme.",
        type: "photo",
        src: "/salon_beaute.jpeg",
        alt: "Salon de beauté premium",
      },
      {
        label: "Réserver",
        caption: "Réservation en ligne et mise en avant de votre expertise.",
        type: "photo",
        src: "/site_salon.jpeg",
        alt: "Interface du site du salon de beauté",
      },
    ],
  },
  {
    id: 10,
    name: "Autre",
    category: "Projet personnalisé",
    description: "Un site sur mesure pour toute autre activité, Ã  partir de votre besoin précis.",
    gradient: "from-zinc-500/20 via-stone-500/10 to-slate-500/5",
    accentColor: "zinc",
    mockup: "✨",
    features: ["Sur mesure", "Besoin précis", "Contact", "Adaptation"],
    testimonial: "Chaque projet peut Ãªtre pensé pour une réalité différente.",
    slides: [
      {
        label: "L'univers",
        caption: "Une expérience digitale pensée pour votre activité, quel que soit votre secteur.",
        type: "photo",
        src: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=1200&q=80&auto=format&fit=crop",
        alt: "Projet personnalisé",
      },
      {
        label: "Réserver",
        caption: "Contactez-nous pour créer quelque chose d'adapté Ã  votre activité.",
        type: "photo",
        src: "/site_autre.png",
        alt: "Interface de site web personnalisé",
      },
      {
        label: "Nos clients",
        caption: "Des projets uniques réalisés sur mesure pour des entrepreneurs de tous secteurs, avec une approche flexible et adaptée Ã  chaque besoin.",
        type: "photo",
        src: "/autre_client.jpeg",
        alt: "Clients et projets personnalisés réalisés par l'agence",
      },
    ],
  },
];

